---
- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - cmake
    - csh
    - flex
    - g++
    - gfortran
    - gcc
    - git
    - libbz2-dev
    - libfreetype6-dev
    - liblapack-dev
    - libatlas-dev
    - libopenmpi-dev
    - openmpi-bin
    - openmpi-common
    - patch
    - python-matplotlib
    - python-dev
    - python-pip
    - python-tk
    - software-properties-common
    - tar
    - time
    - wget

- name: pip install python modules
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - Cython
    - mako
    - numpy
    - scipy
    - virtualenv

- name: unarchive ambertools
  unarchive: src={{ ambertools_url }} dest=/usr/local copy=no

- name: configure ambertools single thread
  command: ./configure -noX11 gnu chdir=/usr/local/amber14
  environment:
    AMBERHOME: /usr/local/amber14
    PATH: "$PATH:/usr/lib64/openmpi/bin:/usr/local/amber14/bin"
    LD_LIBRARY_PATH: /usr/local/amber14/lib

- name: make install ambertools single thread
  command: make install chdir=/usr/local/amber14
  environment:
    AMBERHOME: /usr/local/amber14
    PATH: "$PATH:/usr/lib64/openmpi/bin:/usr/local/amber14/bin"
    LD_LIBRARY_PATH: /usr/local/amber14/lib
