---
# TODO not yet modified for ambertools

- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - cmake
    - csh
    - flex
    - g++
    - gfortran
    - gcc
    - git
    - libbz2-dev
    - libfreetype6-dev
    - liblapack-dev
    - libatlas-dev
    - libopenmpi-dev
    - openmpi-bin
    - openmpi-common
    - patch
    - python-matplotlib
    - python-dev
    - python-pip
    - python-tk
    - software-properties-common
    - tar
    - time
    - wget

- name: pip install python modules
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - Cython
    - mako
    - numpy
    - scipy
    - virtualenv

- name: clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes
  with_items:
    - { repo: "https://github.com/haddocking/{{ haddock_app }}.git", dest: "/usr/local/{{ haddock_app }}" }

- name: wget nvidia driver
  get_url: url={{ nvidia_url }} dest=/usr/local mode=700

- name: unarchive opencl headers
  unarchive: src={{ opencl_url }} dest=/usr/include copy=no

- name: install nvidia driver
  command: ./{{ nvidia_driver }} -s --no-kernel-module chdir=/usr/local



- name: pip install and {{ haddock_app }}
  pip: name={{ item }} state=present
  with_items:
    - "file:///usr/local/{{ haddock_app }}"

